//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IotTestEntities : DbContext
    {
        public IotTestEntities()
            : base("name=IotTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_company> tb_company { get; set; }
        public virtual DbSet<tb_contract> tb_contract { get; set; }
        public virtual DbSet<tb_terminal> tb_terminal { get; set; }
        public virtual DbSet<tb_terminal_contract_relation> tb_terminal_contract_relation { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_user_contract_relation> tb_user_contract_relation { get; set; }
    }
}
