//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_company
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public Nullable<int> used_flg { get; set; }
        public string access_key { get; set; }
        public System.DateTime createdate { get; set; }
        public int createuserid { get; set; }
        public System.DateTime updatedate { get; set; }
        public int updateuserid { get; set; }
        public byte[] concurrencykey { get; set; }
    }
}
