//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contract
    {
        public string contract_id { get; set; }
        public int company_id { get; set; }
        public int industry_m_kind { get; set; }
        public string branch_name { get; set; }
        public string customer_id { get; set; }
        public Nullable<int> building_type_id { get; set; }
        public Nullable<int> contract_menu_id { get; set; }
        public string postcode { get; set; }
        public string address { get; set; }
        public Nullable<int> measurement_date { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string service_state { get; set; }
        public Nullable<System.DateTime> service_state_date { get; set; }
        public Nullable<int> meter_difference_time { get; set; }
        public System.DateTime createdate { get; set; }
        public int createuserid { get; set; }
        public System.DateTime updatedate { get; set; }
        public int updateuserid { get; set; }
        public byte[] concurrencykey { get; set; }
    }
}
