//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_contract_relation
    {
        public int user_id { get; set; }
        public string contract_id { get; set; }
        public int authority_id { get; set; }
        public System.DateTime createdate { get; set; }
        public int createuserid { get; set; }
        public System.DateTime updatedate { get; set; }
        public int updateuserid { get; set; }
        public byte[] concurrencykey { get; set; }
    }
}
